

  - name: Dowloading OC clients 
    get_url:
      url: "{{ ocp_client }}"
      dest: /usr/local/src/openshift-client-linux.tar.gz



  - name: Unarchiving OC clients
    unarchive:
      src: /usr/local/src/openshift-client-linux.tar.gz
      dest: /usr/local/bin
      remote_src: yes



  - name: Removing files that are not needed
    file:
      path: /usr/local/bin/README.md
      state: absent

  


 
