
---
# handlers file for juliovp01.rhel-kvm-install



- name: enable_service
  systemd:
    state: started
    name: docker
    enabled: yes

- name: cleanup openshift login
  file: path="{{ kubeconfig | dirname }}" state=absent

